import React from "react";
import image1 from "../assets/images/image1.webp";
import image2 from "../assets/images/image2.webp";

const ArticlesContext = React.createContext();

export const ArticlesProvider = ({ children }) => {
  const articles = [
    {
      title: "Ugovor o doživotnom izdržavanju",
      desc: "Jedan od bitnih ugovora u naslednom pravu je svakako ugovor o doživotnom izdržavanju. Zaključenju ovog ugovora, kad je naravno reč o naslednom pravu, pristupa najveći broj ljudi, te se može reći da je ugovor o doživotnom izdržavanju svakako jedan od najznačajnijih i najčešćih ugovora u našem pravu. Isti je regulisan Zakonom o nasleđivanju. Ukoliko želite da obezbedite da se neko brine o vama u starosti i/ili bolesti do kraja vašeg života, svakako biste to ishodovali zaključenjem ove vrste ugovora. U slučaju da se obaveze propisane ugovorom ne izvršavaju na način na koji je to dogovoreno, i ovakav ugovor se može raskinuti, kao i svaki drugi dvostrani ugovor, jer jedna strane neispunjava svoju obavezu. Ono što je prvenstveno bitno napomenuti jeste da Ugovor o doživotnom izdržavanju mora biti zaključen u obliku solemnizovane isprave. Zaključenjem ovog ugovora, obavezuje se primalac izdržavanja da se posle njegove smrti na davaoca izdržavanja prenese svojina tačno određenih stvari ili prava, a davalac izdržavanja se obavezuje da ga, kao naknadu za to, izdržava i da se brine o njemu do kraja njegovog života i da ga posle smrti sahrani. Način na koji će se to činiti, zavisi od volja ugovarača. Vrlo je bitno napomenuti, a što je i javni beležnik posebno dužan da upozori ugovarače prilikom overe ovakvog ugovora, jeste da primalac izdržavanja bude svestan da imovina koja je predmet ovog ugovora ne ulazi u njegovu zaostavštinu i da se njom, nakon njegove smrti, ne mogu namiriti njegovi nužni naslednici. O tome mora da se stavi posebna napomena u klauzuli o potvrđivanju jer bi u suprotnom ugovor bio ništav. Česti su slučajevi u praksi da zakonski naslednici primaoca izdržavanja za postojanje ovakvog ugovora saznaju tek na ostavinskoj raspravi. Ukoliko isti smatraju da postoji neki od razloga za poništaj ugovora o doživotnom izdržavanju, zakonski naslednici primaoca izdržavanja imaju pravo da u roku od godinu dana od dana saznanja za ugovor, a najkasnije u roku od 3 godine od smrti primaoca izdržavanja podnesu zahtev za poništaj ugovora. Ukoliko vam je potrebna pravna pomoć za sastavljanje ugovora o doživotnom izdržavanju, raskid, zastupanje ili pak pravni savet u pogledu toga ko sve može zaključiti ovakav ugovor, pod kojim uslovima ili iz kojih razloga možete tražiti poništaj već zaključenog Ugovora o doživotnom izdržavanju, kontaktirajte nas kako biste na najbolji način zaštitili i ostvarili svoja prava.",
      image: image1,
    },
    {
      title: "Naplata duga po osnovu računa - faktura",
      desc: "Naplata potraživanja po osnovu računa ili faktura za isporučene proizvode ili pruženu uslugu predstavlja u nekim situacijama problem za svako lice koje se bavi prodajom ili pružanjem usluga. Republika Srbija ima određene propise koji regulišu ovu oblast i pružaju okvir za efikasnu naplatu potraživanja. Prvi korak u naplati potraživanja je ispostavljanje jasnih i preciznih računa ili faktura drugoj strani, kupcima. Račun ili faktura treba sadržati sve relevantne informacije, kao što su naziv i adresa prodavca i kupca, detaljan opis proizvoda ili usluga, količina, cena, datum izdavanja, rok plaćanja i detalji za uplatu. Kada dođe do kašnjenja ili neplaćanja računa, lice koje je isporučilo fakturu treba da preduzme odgovarajuće korake u skladu sa zakonskim propisima kako bi obezbedilo izvršenje obaveze po osnovu isporučenih računa. Prva mera koju lice mora da preduzme je da obavesti drugu stranu, kupca da postoji neplaćeni račun. Najčešće se druga strana obaveštava slanjem opomene u pisanoj formi, kojom se ukazuje na dospelu obavezu za plaćanje. Opomena treba biti jasna, mora da sadrži relevantne informacije o potraživanju i mora se ostaviti rok drugoj strani za dobrovoljno izvršenje plaćanja računa, Ukoliko druga strana, kupac ne izvrši plaćanje ni nakon opomene, ispunjeni su uslovi i može se pokrenuti sudski postupak radi naplate potraživanja. Sudski postupak može uključivati podnošenje tužbe protiv kupca i aktivno učestvovanje u postupku kako bi se dokazalo postojanje duga i ostvarila naplata potraživanja ili pokretanja izvršnog postupka. U ovoj fazi, važno je imati adekvatnu dokumentaciju, kao što su originalni ugovori, računi, fakture ili druge relevantne dokaze o poslovnoj transakciji. Sudska presuda u korist poverioca omogućava sprovođenje izvršnog postupka, koji podrazumeva prinudnu naplatu potraživanja koje se sprovodi putem Javnih izvršitelja. Međutim, postupak naplate potraživanja može da se pokrene i samo na osnovu računa koji su sastavljeni shodno zakonskim propisima, a koji treba da budu u originalu ili kopiji vernoj originalu, jer oni predstavljaju verodostojnu ispravu po osnovu koje je moguće pokrenuti postupak prinudne naplate potraživanja. Na taj način se može izbeći višegodišnje vođenje sudskog postupka i odugvlačenje naplate neplaćenih računa. Ukoliko dođe do postupka prinudne naplate potraživanja, isto se sprovodi preko Javnih izvršitelja. Načini na koji se prinudnim putem namiruje poverilac u izvršnom postupku je blokada računa dužnika, prodaju imovine ili druge mere u cilju naplate potraživanja. Brzina naplate potraživanja varira od slučaja do slučaja. Važno je naglasiti da je savetovanje sa advokatom od ključne važnosti u ovom procesu, kako bi se izvršila provera dokumentacije koje poverilac poseduje, dala procena uspešnosti naplate, a sve u cilju osiguranja poštovanja svih zakonskih propisa i pravila koja se odnose na naplatu potraživanja.",
      image: image2,
    },
  ];

  return (
    <ArticlesContext.Provider value={{ articles }}>
      {children}
    </ArticlesContext.Provider>
  );
};

export default ArticlesContext;
